version: '2'
services:
  web:
    image: node:6.0
    volumes:
      - "/home/docker_u/Desktop/nodekick-docker/nodekick/:/app"
    working_dir: /app
    restart: always
    expose:
      - "3000"
    ports:
      - "8080:3000"
    command: node server.js
