version: '2'
services:
  web:
    image: node:6.0
    volumes:
      - "/home/docker_u/Desktop/webfinder-docker/word-finder/:/app"
    working_dir: /app
    restart: always
    expose:
      - "3000"
    ports:
      - "8000:3000"
    command: node start.js

